### ISSUE TITLE
Unable to resolve module `react-native-paystack-webView`

### ISSUE THREAD

**Issue by EmekaIwuagwu** [just1and0/React-Native-Paystack-WebView#41]
I am getting this as an Error, trying to use the Demo i saw on the internet having followed a tut from youtube

The full Error is given thus :

error: Error: Unable to resolve module `react-native-paystack-webView` from `src\Payments.js`: react-native-paystack-webView could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (D:\reacttut\nosdra\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (D:\reacttut\nosdra\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\reacttut\nosdra\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (D:\reacttut\nosdra\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at dependencies.map.result (D:\reacttut\nosdra\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31)
    at Array.map (<anonymous>)
    at resolveDependencies (D:\reacttut\nosdra\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at D:\reacttut\nosdra\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\reacttut\nosdra\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

**Comment by eakenbor** [comment]
@EmekaIwuagwu were you able to get a solution? I am having the same problem.

**Comment by tobioyelekan** [comment]
Also having this issue @just1and0 , how do we solve this problem ?

**Comment by eakenbor** [comment]
Installing react-native-webview solved it for me. The instruction is actually hidden somewhere in the documentation. The owner should make it more visible.

**Comment by tobioyelekan** [comment]
> Installing react-native-webview solved it for me. The instruction is actually hidden somewhere in the documentation. The owner should make it more visible.

oh yea, almost like I didn't even do anything, it just started working :)

**Comment by just1and0** [comment]
Hey, i think @eakenbor  found the solution for this, so I'm going to go ahead and close this issue. Big thank @eakenbor for the help.

**Comment by Gentlekboy** [comment]
I had this same error with all required packages installed - Expo bare workflow (TypeScript).
I solved it with the workaround below:

THIS
`import { Paystack } from "react-native-paystack-webview/lib";`

instead of 
`import  { Paystack }  from 'react-native-paystack-webview';`

Pretty new to the react native ecosystem so I can't exactly explain why it worked, but it did anyways. Lool
